Repository Andrey529/LetiPrint, pull requests merged in 2023-03, with the labels that each got.

#17 feat(PrintOrderTaskApp): added sample, that can do print order task
  Examples/PrintOrderTask/.gitignore
  Examples/PrintOrderTask/CMakeLists.txt
  Examples/PrintOrderTask/main.cpp
Labels: Type: Enhancement, For: Embedded, Priority: High, Status: Review needed

#18 fix(BackendService):added correct Dockerfile
  BackendService/Dockerfile
  BackendService/src/main/java/com/example/backendservice/controller/BackendController.java
  BackendService/src/main/java/com/example/backendservice/service/BackendService.java
Labels: Type: Enhancement, For: Backend, For: Automatization, Priority: High, Status: Review needed

#27 25-feat(IoTService): added the functionality of setting a print order from a docker container
  IoTService/Dockerfile
  IoTService/cups_server/Dockerfile
  IoTService/cups_server/cupsd.conf
  IoTService/cups_server/docker-compose.yml
  IoTService/docker-compose.yml
  IoTService/src/main.cpp
Labels: Type: Enhancement, For: Embedded, Priority: High, Status: Review needed

#28 21 get data from matrix keyboard
  EmbeddedService/.gitignore
  EmbeddedService/CMakeLists.txt
  EmbeddedService/src/main.cpp
Labels: Type: Enhancement, For: Embedded, Priority: Medium, Status: Review needed

#30 29 make primary tg bot
  LetiPrintBot/.gitignore
  LetiPrintBot/mvnw
  LetiPrintBot/mvnw.cmd
  LetiPrintBot/pom.xml
  LetiPrintBot/src/main/java/com/example/letiprintbot/LetiPrintBotApplication.java
  LetiPrintBot/src/main/java/com/example/letiprintbot/config/BotConfig.java
  LetiPrintBot/src/main/java/com/example/letiprintbot/config/BotInitializer.java
  LetiPrintBot/src/main/java/com/example/letiprintbot/httpClient/HttpController.java
  LetiPrintBot/src/main/java/com/example/letiprintbot/metaData/MetaData.java
  LetiPrintBot/src/main/java/com/example/letiprintbot/service/LetiPrintBot.java
  LetiPrintBot/src/main/resources/application.properties
Labels: Type: Enhancement, Priority: Medium, Status: Review needed, For: TelegramBot

#34 feat(EmbeddedService): added Dockerfile and docker-compose file
  EmbeddedService/Dockerfile
  EmbeddedService/docker-compose.yml
Labels: Type: Enhancement, For: Embedded, Priority: High, Status: Review needed

#36 feat(IoTService): merged EmbeddedService into IoTService
  IoTService/CMakeLists.txt
  IoTService/Dockerfile
  IoTService/docker-compose.yml
  IoTService/src/main.cpp
Labels: Type: Enhancement, For: Embedded, Priority: High, Status: Review needed
